stages:
  - validate
  - security
  - e2e

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "DEVELOP"
    - if: $CI_COMMIT_BRANCH == "main"


# TEST A FAIRE AVEC QUE LE MERGE PASSE SUR DEVELOP
#INTEGRATION
validate_lint:
  image: node:lts-trixie-slim
  stage: validate
  script:
    - npm ci
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "DEVELOP"

#SONARQUBE
#TRIVY
#BUILD

#A FAIRE QUAND ON MERGE LA BRANCHE DEVELOP SUR LA BRANCHE MAIN
#REFAIRE TOUT CE QUI A ETAIT FAIT AVANT

#TEST VULNERABILITE

#TEST SECURITE
dependency_scan:
  image: node:lts-trixie-slim
  stage: security
  script:
    - npm ci
    - npm audit --audit-level=high
  rules:
    - if: $CI_COMMIT_BRANCH == "DEVELOP"

#A FAIRE QUAND UN MERGE EST DETECTE SUR LA BRANCHE MAIN

#TEST QUALITE

#TEST E2E
test_e2e:
  image: node:lts-trixie-slim
  stage: e2e
  script:
    - npm ci
    - npm run build
    - npm run test:e2e
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

#GENERATION ARTIFACT

#GENERATION IMAGE

#PUSH IMAGE SUR REPO PRIVEE

