
stages:          
  - validate

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "main"

lint:
  stage: validate
  script:
    - npm run list
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"