stages:
  - validate
  - security
  - e2e
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "DEVELOP"

validate_lint:
  image: node:lts-trixie-slim
  stage: validate
  script:
    - npm ci
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "DEVELOP"

dependency_scan:
  image: node:lts-trixie-slim
  stage: security
  script:
    - npm ci
    - npm audit --audit-level=high
  rules:
    - if: $CI_COMMIT_BRANCH == "DEVELOP"

test_e2e:
  image: node:lts-trixie-slim
  stage: e2e
  script:
    - npm ci
    - npm run build
    - npm run test:e2e
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

deploy_app:
  image: alpine:3.20
  stage: deploy
  script:
    - echo "Start deploy"
    - echo "Deploy finished"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  allow_failure: true

