
stages:          
  - validate
  - security

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "main"

lint:
  image: node:lts-trixie-slim
  stage: validate
  script:
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


dependecy_scan:
  image: node:lts-trixie-slim
  stage: security
  script:
    - npm ci
    - npm audit --aduit-level=high
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  
