stages:
  - validate
  - security

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "develop"


debug_ci:
  stage: validate
  image: node:lts-trixie-slim
  script:
    - echo "SOURCE=$CI_PIPELINE_SOURCE"
    - echo "BRANCH=$CI_COMMIT_BRANCH"
    - echo "TARGET=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  rules:
    - when: always


validate_lint:
  image: node:lts-trixie-slim
  stage: validate
  script:
    - npm ci
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "DEVELOP"

dependency_scan:
  image: node:lts-trixie-slim
  stage: security
  script:
    - npm ci
    - npm audit --audit-level=high
  rules:
    - if: $CI_COMMIT_BRANCH == "DEVELOP" && $CI_PIPELINE_SOURCE == "push"
